### PR TITLE
Better support for Docker

### PR DESCRIPTION
**Pull request by wildsurfer**
- image is now ready to be uploaded to Docker Hub;
- InfluxDb and Grafana removed to follow Docker best practices. See
  https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/run-only-one-process-per-container
  for more info;
- README updated with docker and docker-compose examples;

### CODE REVIEW

**Comment by wildsurfer** [comment]
@sanathp, I recommend to add this docker image to Docker Hub right after merging this PR (if you like it for sure) to match naming conventions used by me in README file

**Comment by sanathp** [comment]
Thanks for this pull request.

Will test it when i get some time.

**Comment by wildsurfer** [comment]
ping ;)

**Comment by otraore** [comment]
@sanathp Have you forgotten about this PR?

**Comment by wildsurfer** [comment]
:(

**Comment by timelf123** [comment]
This should be merged

**Comment by BobCashStory** [comment]
i did use it and it work well

**Comment by BobCashStory** [comment]
@sanathp thanks !

**Pull request merged**
